In [5]:
pip install numpy

Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
# 1.1创建一个一维数组
d1 = np.array([1,2,3,4,5])
d1

array([1, 2, 3, 4, 5])

In [8]:
# 属性：size数据大小
d1.size

5

In [9]:
# 属性：type数据类型
d1.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [10]:
type(d1)

numpy.ndarray

In [11]:
# 属性：ndim数据维度
d1.ndim

1

In [12]:
# 1.2创建二维数组
d2 = np.arange(15)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# 增加行、列维度
d2 = d2.reshape(3,5)
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
# 打印一下相关属性
d2.size

15

In [15]:
d2.ndim

2

In [16]:
type(d1)

numpy.ndarray

In [17]:
# numpy官网地址：numpy.org / numpy.org.cn
np.array?