## 1.3.1 索引

* 单个元素索引：一维数组、负数索引
* 二维数组的索引

## 1.3.2 切片

* 切片
* 跨步
* 索引数组：针对多维数组的索引
* 索引结合切片

*更多参考：[NumPy中文网-索引部分](https://www.numpy.org.cn/user/basics/indexing.html#%E8%B5%8B%E5%80%BC%E4%B8%8E%E5%BC%95%E7%94%A8)*

In [1]:
import numpy as np

In [2]:
# 1.3.1 一维数组索引
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [3]:
# 取第4个数值
array1[3]

4

In [4]:
array1[-2]

4

In [5]:
# 二维数组
array2 = np.arange(14).reshape(2, 7)
array2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [6]:
array2[0, 3]  # 第一行第四个

3

In [7]:
array2[0][3]  # 这个语法和上面是一样的

3

In [6]:
array2[1, -1]

13

In [7]:
array2[1, -2]

12

In [10]:
array2[-1, -1]  # 第一个-1 代表是最后一行的

13

In [8]:
# 三维数组
array3 = np.arange(30).reshape(2, 3, 5)
array3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [9]:
array3[0, 1, 2]

7

In [10]:
array3[0][1][2]

7

In [11]:
# 1.3.2 切片
array1

array([1, 2, 3, 4, 5])

In [15]:
array1[0:3]  # a~b，a<=x<b

array([1, 2, 3])

In [16]:
array1[2:6]

array([3, 4, 5])

In [17]:
array1[2:]  #从第三个到最后一个

array([3, 4, 5])

In [18]:
array1[:-1]

array([1, 2, 3, 4])

In [12]:
# 二维数组切片
array2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [13]:
array2[1:, :]  # 行参数、列参数   针对行我要第二行,针对列我全要

array([[ 7,  8,  9, 10, 11, 12, 13]])

In [14]:
array2[:, 3:4]   # 只要第四列的数据

array([[ 3],
       [10]])

In [22]:
array2[1:, 3:4]

array([[10]])

In [15]:
# 三维数组
array3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [24]:
array3[0:1, 2:, :]

array([[[10, 11, 12, 13, 14]]])

In [25]:
array3[0:1, 2:, :][2]

IndexError: index 2 is out of bounds for axis 0 with size 1

In [16]:
array3[0:1, 2:, :][0, 0, 2]  # 索引结合切片

12

In [17]:
# 索引多个数值
array1

array([1, 2, 3, 4, 5])

In [18]:
array1[np.array([0, 2, 4])]

array([1, 3, 5])

In [19]:
# 二维数组
array2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [20]:
array2[np.array([0, 1]), np.array([1, 2])]

array([1, 9])