In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import preprocessing as prep

In [2]:
# 3.4.1 自然编码 vs 独热编码

In [3]:
# 自然编码：0,1 -> female:0
# 独热编码：male -> [0,1]  from Europe -> [0,0,1,0]
genders = ['female', 'male'] 
locations = ['from Africa', 'from Asia', 'from Europe', 'from US']
browsers = ['uses Chrome', 'uses Firefox', 'uses IE', 'uses Safari']

In [4]:
# 3.4.2 将定类特征转换为二进制

In [10]:
# 创建模型 -> fit训练数据 -> transform显示数据 -> .attribute打印属性
onehot = prep.OneHotEncoder(categories=[genders,locations,browsers],
                            sparse=False, handle_unknown='ignore')
onehot.fit_transform([['female','from Asia', 'uses Chrome']])

array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 0.]])

In [11]:
onehot.fit_transform([['female','xxyyzz', 'uses Chrome']])

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [12]:
onehot.fit_transform([['female','from Asia', 'uses Chrome'],
                     ['male','from US', 'uses Safari']])

array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 1.]])